# environment.yml
name: tf2-keras
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - tensorflow-gpu=2.10
  - keras
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - ipykernel
  - pip
  - pip:
    - keras-tuner
    - tensorflow-hub